const express = require('express');
const pool = require('../utils/db');
const bcrypt = require('bcrypt');
const result = require('../utils/result')

const router = express.Router();


const validateEmail = (email) => {
    const re = /\S+@\S+\.\S+/;
    return re.test(email);
};

router.get('/', (req, res) => {
    const sql = `SELECT * FROM users`
    pool.query(sql, (error, data) => {
        res.send(result.createResult(error, data))
    })
})

router.post('/', (req, res) => {
    // const body = req.body
    // console.log(body)

    //Object Destructuring
    const { name, email, password, mobile, city } = req.body

    const sql = `INSERT INTO users(name,email,password,mobile,city) 
    VALUES('${name}','${email}','${password}','${mobile}','${city}')`

    //console.log(sql)
    // res.send()

    pool.query(sql, (error, data) => {
        if (data)
            res.send(data)
        else
            res.send(error)
    })
})


// POST /users (Registration/Sign Up)
router.post('/', async (req, res) => {
    const { firstName, lastName, email, password, mobile, birth } = req.body;

    // Basic input validation as required by points
    if (!firstName || !lastName || !email || !password) {
        return res.status(400).json({ message: 'Missing required fields' });
    }
    if (!validateEmail(email)) {
        return res.status(400).json({ message: 'Invalid email format' });
    }

    try {
        // Hash the password securely
        const saltRounds = 10;
        const hashedPassword = await bcrypt.hash(password, saltRounds);

        const query = `
            INSERT INTO users (first_name, last_name, email, password, mobile, birth)
            VALUES (?, ?, ?, ?, ?, ?)
        `;
        // User/review id for new user/review should be auto-generated by MySQL
        const [result] = await db.execute(query, [firstName, lastName, email, hashedPassword, mobile || null, birth || null]);

        res.status(201).json({ 
            message: 'User registered successfully', 
            userId: result.insertId 
        });

    } catch (error) {
        if (error.code === 'ER_DUP_ENTRY') {
            return res.status(409).json({ message: 'Email already registered' });
        }
        console.error(error);
        res.status(500).json({ message: 'Server error during registration' });
    }
});

// POST /api/v1/users/login (Sign In)
router.post('/login', async (req, res) => {
    const { email, password } = req.body;

    if (!email || !password) {
        return res.status(400).json({ message: 'Missing email or password' });
    }

    try {
        // Retrieve user from the database
        const query = 'SELECT id, password FROM users WHERE email = ?';
        const [rows] = await db.execute(query, [email]);

        if (rows.length === 0) {
            return res.status(401).json({ message: 'Invalid credentials' });
        }

        const user = rows[0];
        // Compare the submitted password with the hashed password in the database
        const isMatch = await bcrypt.compare(password, user.password);

        if (!isMatch) {
            return res.status(401).json({ message: 'Invalid credentials' });
        }
        
        // In a real application, you would generate a JWT token here and send it back
        res.status(200).json({ 
            message: 'Login successful', 
            userId: user.id,
            token: 'fake-jwt-token-12345'
        });

    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'Server error during login' });
    }
});


// Add routes for Edit Profile, Change Password, Logout, etc. similarly

module.exports = router;
